
package capaGrafica;

import capaLogica.Recursividad;
import estructuras.ListaSimple;
import javax.swing.JOptionPane;





public class FrmExamen2 extends javax.swing.JFrame {
private ListaSimple lista = new ListaSimple();
  
    public FrmExamen2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtHilera = new javax.swing.JTextField();
        jTxtN1 = new javax.swing.JTextField();
        jTxtN2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxaResultado = new javax.swing.JTextArea();
        jBtnEliminarNodos = new javax.swing.JButton();
        jBtnSubHilera = new javax.swing.JButton();
        jBtnLlenarLista = new javax.swing.JButton();
        jBtnContarMayusculas = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jBtnRestaRecursiva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Programación II - Examen II");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Hilera");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("N1");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("N2");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Resultados");

        jTxtHilera.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jTxtN1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jTxtN2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jTxaResultado.setColumns(20);
        jTxaResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxaResultado.setRows(5);
        jScrollPane1.setViewportView(jTxaResultado);

        jBtnEliminarNodos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBtnEliminarNodos.setText("Eliminar Nodos");
        jBtnEliminarNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarNodosActionPerformed(evt);
            }
        });

        jBtnSubHilera.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBtnSubHilera.setText("SubHilera");
        jBtnSubHilera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubHileraActionPerformed(evt);
            }
        });

        jBtnLlenarLista.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBtnLlenarLista.setText("Llenar Lista");
        jBtnLlenarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLlenarListaActionPerformed(evt);
            }
        });

        jBtnContarMayusculas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBtnContarMayusculas.setText("Contar Mayúsculas");
        jBtnContarMayusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnContarMayusculasActionPerformed(evt);
            }
        });

        jBtnSalir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jBtnRestaRecursiva.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBtnRestaRecursiva.setText("Resta Recursiva (N1-N2)");
        jBtnRestaRecursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRestaRecursivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtN1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(jTxtN2))
                            .addComponent(jTxtHilera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnLlenarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnSubHilera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnContarMayusculas, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jBtnEliminarNodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnRestaRecursiva, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtHilera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLlenarLista))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEliminarNodos)
                        .addGap(16, 16, 16)
                        .addComponent(jBtnSubHilera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnContarMayusculas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jBtnRestaRecursiva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLlenarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLlenarListaActionPerformed
String hilera= jTxtHilera.getText();
lista.llenarLista(hilera);
jTxaResultado.setText(lista.toString());

jTxtHilera.requestFocus();
jTxtHilera.selectAll();
    }//GEN-LAST:event_jBtnLlenarListaActionPerformed

    private void jBtnEliminarNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarNodosActionPerformed

     String hileraInvertida = lista.eliminarNodos();
     jTxaResultado.setText(hileraInvertida);
     jTxtHilera.requestFocus();
     jTxtHilera.selectAll();
    }//GEN-LAST:event_jBtnEliminarNodosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          jTxtHilera.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void jBtnSubHileraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubHileraActionPerformed
//        int n1 = 0;
//        int n2 = 0;
//        try {
//            n1 = Integer.parseInt(jTxtN1.getText());
//            n2 = Integer.parseInt(jTxtN2.getText());
//        } catch (NumberFormatException numberFormatException) {
//        }
//      String hola= String.valueOf(lista.subHilera(n1, n2));
//   
//      jTxaResultado.setText(lista.toString() + "\nSub Hilera:  "+ hola);
//      //jTxaResultado.append(n1 != -1 ? "El valor se encuentra en la posición " +n1
//                //: "El valor no se encuentra en la lista");
//      jTxtN1.requestFocus();
//      jTxtN2.requestFocus();
//      jTxtN1.selectAll();
//      jTxtN2.selectAll();


// Nuevo

int n1 = 0;
int n2 = 0;
try {
    n1 = Integer.parseInt(jTxtN1.getText());
    n2 = Integer.parseInt(jTxtN2.getText());
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Los valores ingresados no son válidos", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

String subhilera = lista.subHilera(n1, n2);
jTxaResultado.setText(lista.toString() + "\nSub Hilera: " + subhilera);

jTxtN1.requestFocus();
jTxtN1.selectAll();
    }//GEN-LAST:event_jBtnSubHileraActionPerformed

    private void jBtnContarMayusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnContarMayusculasActionPerformed
     int cont=lista.contarMayúsculas();
    // jTxaResultado.setText(lista.toString());
    jTxaResultado.setText("Cantidad de mayúsculas: " + cont + "\n" + lista.toString());
     jTxtHilera.requestFocus();
     jTxtHilera.selectAll();
    }//GEN-LAST:event_jBtnContarMayusculasActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnRestaRecursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRestaRecursivaActionPerformed
    int x, y;
    x = Integer.parseInt(jTxtN1.getText());
    y = Integer.parseInt(jTxtN2.getText());
    
    jTxaResultado.setText("Resta: "+ Recursividad.restar(x, y));
    
    }//GEN-LAST:event_jBtnRestaRecursivaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnContarMayusculas;
    private javax.swing.JButton jBtnEliminarNodos;
    private javax.swing.JButton jBtnLlenarLista;
    private javax.swing.JButton jBtnRestaRecursiva;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jBtnSubHilera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxaResultado;
    private javax.swing.JTextField jTxtHilera;
    private javax.swing.JTextField jTxtN1;
    private javax.swing.JTextField jTxtN2;
    // End of variables declaration//GEN-END:variables
}
